version: '3.8'

services:
  app:
    container_name: plugin_app
    build: .
    command: bash -c "
      pip install -r requirements.txt &&
      python manage.py makemigrations PluginBackend Web &&
      python manage.py migrate &&
      python manage.py loaddata PluginBackend/json/data.json &&
      gunicorn PluginRepository.wsgi:application --bind 0.0.0.0:8000"
#      python manage.py runserver 127.0.0.1:8000"
    restart: unless-stopped
    ports:
      - 7090:8000
    environment:
      - DEBUG=0
#      - SECRET_KEY=secret
#      - ALLOWED_HOSTS=localhost

    volumes:
      - /srv/plugin/data:/data

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/16