# Generated by Django 3.2.9 on 2021-11-25 16:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('code', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PluginVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='plugins/')),
                ('file_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PluginBackend.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='PluginServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PluginBackend.plugin')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PluginBackend.server')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PluginBackend.pluginversion')),
            ],
        ),
    ]
