# Generated by Django 3.2.9 on 2021-12-05 14:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(default='-1', max_length=10)),
                ('folder_name', models.CharField(max_length=50)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PluginVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='PluginBackend/plugins/')),
                ('file_name', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PluginBackend.plugin')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('port', models.CharField(default='25565', max_length=10)),
                ('server_id', models.CharField(default='', max_length=50)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServerPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='null', max_length=100)),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PluginBackend.plugin')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PluginBackend.server')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='PluginBackend.pluginversion')),
            ],
        ),
    ]
